version: '3.3'
services:
  map:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/bash", "/map/docker-launch.sh"]
    volumes:
      - .:/map
    ports:
      - "8000:8000"
